
service:

  app:
    build: ./
    container_name: main-app
    volumes:
      - $PWD:/app
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - ktor-network
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1-alpine
    hostname: postgres
    ports:
      - 5432
    restart: always
    environment:
      POSTGRES_DB: training_kotlin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    networks:
      - ktor-network

networks:
  ktor-network:
    driver: bridge